# Deep Learning

- Mathias Lettere
- 09-11-2023


## Importación de los datos

In [1]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


## Exploración de los datos

In [2]:
train_images.shape

(60000, 28, 28)

In [4]:
len(train_labels)

60000

In [6]:
test_images.shape

(10000, 28, 28)

In [7]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [8]:
from tensorflow import keras
from tensorflow.keras import layers
model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
])

## Optimizador y función de pérdida

In [9]:
model.compile(optimizer="rmsprop",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

## Preprocesamiento

In [11]:
train_images=train_images.reshape((60000, 28*28))
train_images=train_images.astype("float32")/255

test_images=test_images.reshape((10000, 28*28))
test_images=test_images.astype("float32")/255

## Entrenamiento

In [12]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 7s 14ms/step - loss: 2.2385 - accuracy: 0.2517
Epoch 2/5
469/469 [==============================] - 5s 12ms/step - loss: 1.6840 - accuracy: 0.5920
Epoch 3/5
469/469 [==============================] - 7s 14ms/step - loss: 1.0481 - accuracy: 0.7482
Epoch 4/5
469/469 [==============================] - 5s 12ms/step - loss: 0.7489 - accuracy: 0.8113
Epoch 5/5
469/469 [==============================] - 6s 13ms/step - loss: 0.6039 - accuracy: 0.8411


## Predicción

In [13]:
test_digits=test_images[0:10]
predictions=model.predict(test_digits)
predictions[0]

1/1 [==============================] - 0s 90ms/step


array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.99999994, 0.        , 0.        ],
      dtype=float32)

In [14]:
predictions[0].argmax()

7

In [15]:
predictions[0][7]

0.99999994

### Etiqueta de evaluación

In [16]:
test_labels[0]

7

## Evaluación de la precisión

In [17]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

313/313 [==============================] - 1s 3ms/step - loss: 49.3021 - accuracy: 0.7302


# Representación de Datos para NN (con tensores)

In [18]:
#Escalar (tensor rango 0)
import numpy as np
x=np.array(12)
x

array(12)

In [19]:
x.ndim

0

In [20]:
#Vectores (tenso rango 1)
x=np.array([2,3,4,5,7,15])
x

array([ 2,  3,  4,  5,  7, 15])

In [21]:
x.ndim

1

In [22]:
#Matrices (tenso rango 2)
x=np.array([[5,78,2,34,0],
            [6,79,3,35,1],
            [7,80,4,36,2]])
x

array([[ 5, 78,  2, 34,  0],
       [ 6, 79,  3, 35,  1],
       [ 7, 80,  4, 36,  2]])

In [23]:
x.ndim

2

In [24]:
#Tensores rango 3 y más
x = np.array([[[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]],
[[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]],
[[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]]])
x

array([[[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]]])

In [25]:
x.ndim

3